networks:
  traefik:
    external: true
    name: traefik

services:
  api:
    build:
      context: ../server
      dockerfile: ../docker/build/api.dockerfile
    ports:
      - "9000:4000"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable.true"
      - "traefik.http.routers.quiz-client.rule=Host(`quiz.berta.ua`)"